package org.zhongsoft.pendtasks;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PendingTaskPortService service = new PendingTaskPortService();
 * PendingTaskPortServiceSoap portType = service.getPendingTaskPortServiceSoap();
 * portType.addTasks(...);
 * </pre>
 * 
 * </p>
 * 
 */
//@WebServiceClient(name = "PendingTaskPortService", targetNamespace = "http://pendtasks.zhongsoft.org/", wsdlLocation = "file:/I:/Users/raowb/Desktop/WebServiceZS/PendingTaskPortService.wsdl")
//@WebServiceClient(name = "PendingTaskPortService", targetNamespace = "http://pendtasks.zhongsoft.org/", wsdlLocation = "http://27.17.18.12:1000/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl")
@WebServiceClient(name = "PendingTaskPortService", targetNamespace = "http://pendtasks.zhongsoft.org/", wsdlLocation = "http://csepdi-kcsj1/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl")
public class PendingTaskPortService extends Service {

	private final static URL PENDINGTASKPORTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.zhongsoft.pendtasks.PendingTaskPortService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.zhongsoft.pendtasks.PendingTaskPortService.class
					.getResource(".");
			//url = new URL(baseUrl,"file:/I:/Users/raowb/Desktop/WebServiceZS/PendingTaskPortService.wsdl");
			//url = new URL(baseUrl,"http://27.17.18.12:1000/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl");
			url = new URL(baseUrl,"http://csepdi-kcsj1/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl");
		} catch (MalformedURLException e) {
			//logger.warning("Failed to create URL for the wsdl Location: 'file:/I:/Users/raowb/Desktop/WebServiceZS/PendingTaskPortService.wsdl', retrying as a local file");
			//logger.warning("Failed to create URL for the wsdl Location: 'http://27.17.18.12:1000/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl', retrying as a local file");
			logger.warning("Failed to create URL for the wsdl Location: 'http://csepdi-kcsj1/Portal/Sys/SOA/PendingTaskPortService.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PENDINGTASKPORTSERVICE_WSDL_LOCATION = url;
	}

	public PendingTaskPortService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PendingTaskPortService() {
		super(PENDINGTASKPORTSERVICE_WSDL_LOCATION, new QName(
				"http://pendtasks.zhongsoft.org/", "PendingTaskPortService"));
	}

	/**
	 * 
	 * @return returns PendingTaskPortServiceSoap
	 */
	@WebEndpoint(name = "PendingTaskPortServiceSoap")
	public PendingTaskPortServiceSoap getPendingTaskPortServiceSoap() {
		return super
				.getPort(new QName("http://pendtasks.zhongsoft.org/",
						"PendingTaskPortServiceSoap"),
						PendingTaskPortServiceSoap.class);
	}

	/**
	 * 
	 * @return returns PendingTaskPortServiceSoap
	 */
	@WebEndpoint(name = "PendingTaskPortServiceSoap12")
	public PendingTaskPortServiceSoap getPendingTaskPortServiceSoap12() {
		return super.getPort(new QName("http://pendtasks.zhongsoft.org/",
				"PendingTaskPortServiceSoap12"),
				PendingTaskPortServiceSoap.class);
	}

}
