package org.zhongsoft.pendtasks;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PendingTaskPortServiceSoap", targetNamespace = "http://pendtasks.zhongsoft.org/")
public interface PendingTaskPortServiceSoap {

	/**
	 * 
	 * @param errorMsg
	 * @param xml
	 * @param addTasksResult
	 */
	@WebMethod(operationName = "AddTasks", action = "http://pendtasks.zhongsoft.org/AddTasks")
	@RequestWrapper(localName = "AddTasks", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.AddTasks")
	@ResponseWrapper(localName = "AddTasksResponse", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.AddTasksResponse")
	public void addTasks(
			@WebParam(name = "xml", targetNamespace = "http://pendtasks.zhongsoft.org/") String xml,
			@WebParam(name = "AddTasksResult", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<Boolean> addTasksResult,
			@WebParam(name = "errorMsg", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<String> errorMsg);

	/**
	 * 
	 * @param updateTasksResult
	 * @param errorMsg
	 * @param xml
	 */
	@WebMethod(operationName = "UpdateTasks", action = "http://pendtasks.zhongsoft.org/UpdateTasks")
	@RequestWrapper(localName = "UpdateTasks", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.UpdateTasks")
	@ResponseWrapper(localName = "UpdateTasksResponse", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.UpdateTasksResponse")
	public void updateTasks(
			@WebParam(name = "xml", targetNamespace = "http://pendtasks.zhongsoft.org/") String xml,
			@WebParam(name = "UpdateTasksResult", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<Boolean> updateTasksResult,
			@WebParam(name = "errorMsg", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<String> errorMsg);

	/**
	 * 
	 * @param errorMsg
	 * @param xml
	 * @param deleteTasksResult
	 */
	@WebMethod(operationName = "DeleteTasks", action = "http://pendtasks.zhongsoft.org/DeleteTasks")
	@RequestWrapper(localName = "DeleteTasks", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.DeleteTasks")
	@ResponseWrapper(localName = "DeleteTasksResponse", targetNamespace = "http://pendtasks.zhongsoft.org/", className = "org.zhongsoft.pendtasks.DeleteTasksResponse")
	public void deleteTasks(
			@WebParam(name = "xml", targetNamespace = "http://pendtasks.zhongsoft.org/") String xml,
			@WebParam(name = "DeleteTasksResult", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<Boolean> deleteTasksResult,
			@WebParam(name = "errorMsg", targetNamespace = "http://pendtasks.zhongsoft.org/", mode = WebParam.Mode.OUT) Holder<String> errorMsg);

}
